### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by djmtype** [ilrock/gridsome-starter-prismic#7]
In Prismic, I created a Post collection with a UID, Title, Content, and Image fields. 

Created a couple posts. Ran `gridsome develop`.

Getting this error: 
```
TypeError: Cannot read property 'map' of undefined
    at /Users/me/Sites/gridsome-starter-prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:10413
    at /Users/me/Sites/gridsome-starter-prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:10571
    at Array.reduce (<anonymous>)
    at Function.value (/Users/me/Sites/gridsome-starter-prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:10236)
    at Object.t.default [as serialize] (/Users/me/Sites/gridsome-starter-prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:18916)
    at Object.asHtml (/Users/me/Sites/gridsome-starter-prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:4801)
    at Object.keys.forEach (/Users/me/Sites/gridsome-starter-prismic/node_modules/@ilrock/gridsome-source-prismic/utils/index.js:110:40)
    at Array.forEach (<anonymous>)
    at documentParser (/Users/me/Sites/gridsome-starter-prismic/node_modules/@ilrock/gridsome-source-prismic/utils/index.js:96:21)
    at results.forEach (/Users/me/Sites/gridsome-starter-prismic/node_modules/@ilrock/gridsome-source-prismic/index.js:41:31)
    at Array.forEach (<anonymous>)
    at PrismicSource.loadCollections (/Users/me/Sites/gridsome-starter-prismic/node_modules/@ilrock/gridsome-source-prismic/index.js:39:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Am I missing something?

**Comment by djmtype** [comment]
I see there is an open issue with the plugin. 
[https://github.com/ilrock/gridsome-source-prismic/issues/1](https://github.com/ilrock/gridsome-source-prismic/issues/1)
